import { Injectable } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';

@Injectable({
  providedIn: 'root'
})
export class SvgIconsRegistryService {

  constructor(
    private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer
  ) {
    this.matIconRegistry.addSvgIcon(
      `adobephotoshop`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/adobephotoshop.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `angular`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/angular.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `azuredevops`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/azuredevops.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `bitbucket`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/bitbucket.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `bootstrap`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/bootstrap.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `csharp`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/csharp.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `css3`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/css3.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `cypress`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/cypress.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `docker`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/docker.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `dotnet`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/dotnet.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `facebook`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/facebook.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `gimp`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/gimp.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `git`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/git.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `github`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/github.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `gitlab`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/gitlab.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `html5`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/html5.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `java`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/java.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `javascript`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/javascript.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `jirasoftware`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/jirasoftware.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `jquery`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/jquery.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `linux`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/linux.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `linkedin`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/linkedin.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `lodash`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/lodash.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `mariadb`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/mariadb.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `materialdesign`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/materialdesign.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `mongodb`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/mongodb.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `mysql`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/mysql.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `nestjs`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/nestjs.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `nodedotjs`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/nodedotjs.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `npm`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/npm.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `nuxtdotjs`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/nuxtdotjs.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `php`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/php.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `postgresql`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/postgresql.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `postman`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/postman.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `prettier`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/prettier.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `quasar`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/quasar.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `rancher`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/rancher.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `react`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/react.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `reactivex`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/reactivex.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `redux`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/redux.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `sass`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/sass.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `stackoverflow`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/stackoverflow.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `swagger`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/swagger.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `symfony`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/symfony.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `typescript`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/typescript.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `ubuntu`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/ubuntu.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `visualstudio`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/visualstudio.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `visualstudiocode`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/visualstudiocode.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `vuedotjs`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/vuedotjs.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `webpack`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/webpack.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `windows`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/windows.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `woocommerce`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/woocommerce.svg")
    );
    this.matIconRegistry.addSvgIcon(
      `wordpress`,
      this.domSanitizer.bypassSecurityTrustResourceUrl("../assets/icons/wordpress.svg")
    );
    console.log(matIconRegistry)
  }
}
